/**********************************/
/* Table Name: 운동종류 */
/**********************************/
DROP TABLE exertype CASCADE CONSTRAINTS;

CREATE TABLE EXERTYPE(
    EXERCISE_TYPE_NO                  NUMBER(10)     NOT NULL    PRIMARY KEY,
    EXERCISE_TYPE_NAME                VARCHAR2(20)     NULL,
    EXERCISE_TYPE_CNT           NUMBER(7)   NULL
);

COMMENT ON TABLE EXERTYPE is '운동종류';
COMMENT ON COLUMN EXERTYPE.EXERCISE_TYPE_NO is '운동종류번호';
COMMENT ON COLUMN EXERTYPE.EXERCISE_TYPE_NAME is '운동종류명';
COMMENT ON COLUMN EXERTYPE.EXERCISE_TYPE_CNT is '운동개수';

DROP SEQUENCE EXERCISE_TYPE_SEQ;

CREATE SEQUENCE EXERCISE_TYPE_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;
  
INSERT INTO EXERTYPE(EXERCISE_TYPE_NO, EXERCISE_TYPE_NAME,EXERCISE_TYPE_CNT)
  VALUES(EXERCISE_TYPE_SEQ.NEXTVAL, '유산소',0);

INSERT INTO EXERTYPE(EXERCISE_TYPE_NO, EXERCISE_TYPE_NAME,EXERCISE_TYPE_CNT)
  VALUES(EXERCISE_TYPE_SEQ.NEXTVAL, '무산소',0);

COMMIT;